# Generated by Django 5.0.6 on 2024-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationery', 'Stationery'), ('Electronics', 'Electronics'), ('Food', 'Food')], max_length=20, null=True),
        ),
    ]
