# Generated by Django 5.0.6 on 2024-06-26 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="_staff",
            new_name="staff",
        ),
    ]
